package me.paco.datecalculator.util

import me.paco.datecalculator.data.AppLanguage

object LanguageUtils {

    fun getWeekHeaders(language: AppLanguage): List<String> {
        return when (language) {
            AppLanguage.SIMPLIFIED_CHINESE -> listOf("日", "一", "二", "三", "四", "五", "六")
            AppLanguage.TRADITIONAL_CHINESE -> listOf("日", "一", "二", "三", "四", "五", "六")
            AppLanguage.ENGLISH -> listOf("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")
            AppLanguage.JAPANESE -> listOf("日", "月", "火", "水", "木", "金", "土")
            AppLanguage.KOREAN -> listOf("일", "월", "화", "수", "목", "금", "토")
        }
    }

    fun getString(key: String, language: AppLanguage): String {
        val stringsZhCn = mapOf(
            "app_title" to "日期计算器",
            "tab_home" to "首页",
            "tab_calc" to "日期计算",
            "tab_countdown" to "倒数日",
            "tab_anniversary" to "纪念日",
            "tab_lunar" to "农历转换",
            "tab_age" to "年龄计算",
            "settings_language" to "语言设置",
            "settings_theme" to "主题配色方案",
            "settings_dark_mode" to "深色模式",
            "settings_home_config" to "首页功能显示与显隐设置",
            "settings_region" to "选择国家/地区",
            "settings_gps_auto" to "GPS 自动识别所在地",
            "settings_sync_holidays" to "同步最新节假日数据",
            "home_show_screen" to "显示首页",
            "home_calendar" to "月历",
            "home_almanac" to "当日黄历",
            "home_solar_terms" to "二十四节气",
            "home_lunar" to "农历日期",
            "home_zodiac" to "星座与运势",
            "home_weather" to "天气预报",
            "workday" to "工作日",
            "natural_day" to "自然日",
            "solar" to "公历",
            "lunar" to "农历",
            "target_date" to "目标日期",
            "base_date" to "起始日期",
            "settings_title" to "系统设置",
            "history_title" to "历史记录",
            "add_countdown" to "+ 新增倒数日",
            "common_countdown" to "常用倒数日",
            "fixed_countdown" to "固定倒数日",
            "today" to "今天",
            "yesterday" to "昨天",
            "plus_1w" to "+1周",
            "minus_1w" to "-1周",
            "mode_forward" to "加减天数",
            "mode_reverse" to "区间拆算",
            "multi_stage_btn" to "多段模式",
            "add_stage_btn" to "添加下一段时间",
            "save_record" to "保存到记录",
            "diff_natural" to "相差自然日",
            "diff_workday" to "相差工作日",
            "clear_history" to "清空历史",
            "no_history" to "暂无历史记录",
            "select_birth_date" to "选择出生日期",
            "select_start_date" to "选择起始日期",
            "select_target_date" to "选择目标日期",
            "exact_age" to "当前精准年龄",
            "next_birthday_days" to "距离下次生日还有",
            "days_unit" to "天",
            "weeks_unit" to "周",
            "months_unit" to "个月",
            "years_unit" to "岁",
            "total_days" to "生存总天数",
            "total_weeks" to "生存总周数",
            "zodiac_sign" to "生肖属相",
            "constellation" to "星座",
            "days_until_prefix" to "距离",
            "days_until_suffix" to "还有",
            "lucky_number" to "幸运数字",
            "lucky_color" to "幸运颜色",
            "forecast_title" to "当地及未来三日天气推算",
            "add_anniversary" to "+ 新增纪念日",
            "check_in" to "📍 精准打卡",
            "save_anniversary" to "保存纪念日",
            "anniversary_name" to "纪念日名称",
            "anniversary_date" to "纪念日日期",
            "dark_mode_system" to "跟随系统",
            "dark_mode_on" to "开启",
            "dark_mode_off" to "关闭",
            "workday_chip" to "工作日",
            "weekend_chip" to "休息日",
            "result_title_workday" to "工作日计算结果",
            "result_title_natural" to "自然日计算结果"
        )

        val stringsZhTw = mapOf(
            "app_title" to "日期計算器",
            "tab_home" to "首頁",
            "tab_calc" to "日期計算",
            "tab_countdown" to "倒數日",
            "tab_anniversary" to "紀念日",
            "tab_lunar" to "農曆轉換",
            "tab_age" to "年齡計算",
            "settings_language" to "語言設定",
            "settings_theme" to "主題配色方案",
            "settings_dark_mode" to "深色模式",
            "settings_home_config" to "首頁功能顯示與顯隱設定",
            "settings_region" to "選擇國家/地區",
            "settings_gps_auto" to "GPS 自動識別所在地",
            "settings_sync_holidays" to "同步最新節假日數據",
            "home_show_screen" to "顯示首頁",
            "home_calendar" to "月曆",
            "home_almanac" to "當日黃曆",
            "home_solar_terms" to "二十四節氣",
            "home_lunar" to "農曆日期",
            "home_zodiac" to "星座與運勢",
            "home_weather" to "天氣預報",
            "workday" to "工作日",
            "natural_day" to "自然日",
            "solar" to "公曆",
            "lunar" to "農曆",
            "target_date" to "目標日期",
            "base_date" to "起始日期",
            "settings_title" to "系統設定",
            "history_title" to "歷史記錄",
            "add_countdown" to "+ 新增倒數日",
            "common_countdown" to "常用倒數日",
            "fixed_countdown" to "固定倒數日",
            "today" to "今天",
            "yesterday" to "昨天",
            "plus_1w" to "+1周",
            "minus_1w" to "-1周",
            "mode_forward" to "加減天數",
            "mode_reverse" to "區間拆算",
            "multi_stage_btn" to "多段模式",
            "add_stage_btn" to "添加下一段時間",
            "save_record" to "保存到記錄",
            "diff_natural" to "相差自然日",
            "diff_workday" to "相差工作日",
            "clear_history" to "清空歷史",
            "no_history" to "暫無歷史記錄",
            "select_birth_date" to "選擇出生日期",
            "select_start_date" to "選擇起始日期",
            "select_target_date" to "選擇目標日期",
            "exact_age" to "當前精准年齡",
            "next_birthday_days" to "距離下次生日還有",
            "days_unit" to "天",
            "weeks_unit" to "周",
            "months_unit" to "個月",
            "years_unit" to "歲",
            "total_days" to "生存總天數",
            "total_weeks" to "生存總周數",
            "zodiac_sign" to "生肖屬相",
            "constellation" to "星座",
            "days_until_prefix" to "距離",
            "days_until_suffix" to "還有",
            "lucky_number" to "幸運數字",
            "lucky_color" to "幸運顏色",
            "forecast_title" to "當地及未來三日天氣推算",
            "add_anniversary" to "+ 新增紀念日",
            "check_in" to "📍 精準打卡",
            "save_anniversary" to "保存紀念日",
            "anniversary_name" to "紀念日名稱",
            "anniversary_date" to "紀念日日期",
            "dark_mode_system" to "跟隨系統",
            "dark_mode_on" to "開啟",
            "dark_mode_off" to "關閉",
            "workday_chip" to "工作日",
            "weekend_chip" to "休息日",
            "result_title_workday" to "工作日計算結果",
            "result_title_natural" to "自然日計算結果"
        )

        val stringsEn = mapOf(
            "app_title" to "Date Calculator",
            "tab_home" to "Home",
            "tab_calc" to "Date Calc",
            "tab_countdown" to "Countdown",
            "tab_anniversary" to "Anniversary",
            "tab_lunar" to "Lunar Conv",
            "tab_age" to "Age Calc",
            "settings_language" to "Language Settings",
            "settings_theme" to "Theme Color Scheme",
            "settings_dark_mode" to "Dark Mode",
            "settings_home_config" to "Home Screen Display Items",
            "settings_region" to "Country / Region",
            "settings_gps_auto" to "GPS Auto Location Detection",
            "settings_sync_holidays" to "Sync Holiday Data",
            "home_show_screen" to "Show Home Screen",
            "home_calendar" to "Monthly Calendar",
            "home_almanac" to "Almanac",
            "home_solar_terms" to "Solar Terms",
            "home_lunar" to "Lunar Date",
            "home_zodiac" to "Horoscope",
            "home_weather" to "Weather Forecast",
            "workday" to "Workday",
            "natural_day" to "Calendar Day",
            "solar" to "Gregorian",
            "lunar" to "Lunar",
            "target_date" to "Target Date",
            "base_date" to "Start Date",
            "settings_title" to "Settings",
            "history_title" to "History",
            "add_countdown" to "+ Add Countdown",
            "common_countdown" to "Preset Countdowns",
            "fixed_countdown" to "Pinned Countdowns",
            "today" to "Today",
            "yesterday" to "Yesterday",
            "plus_1w" to "+1 Wk",
            "minus_1w" to "-1 Wk",
            "mode_forward" to "Add/Sub Days",
            "mode_reverse" to "Date Interval",
            "multi_stage_btn" to "Multi-Stage",
            "add_stage_btn" to "Add Next Stage",
            "save_record" to "Save Record",
            "diff_natural" to "Calendar Days",
            "diff_workday" to "Workdays",
            "clear_history" to "Clear History",
            "no_history" to "No history records yet",
            "select_birth_date" to "Select Birth Date",
            "select_start_date" to "Select Start Date",
            "select_target_date" to "Select Target Date",
            "exact_age" to "Current Exact Age",
            "next_birthday_days" to "Days until next birthday",
            "days_unit" to "days",
            "weeks_unit" to "weeks",
            "months_unit" to "months",
            "years_unit" to "yrs",
            "total_days" to "Total Days Lived",
            "total_weeks" to "Total Weeks Lived",
            "zodiac_sign" to "Zodiac Animal",
            "constellation" to "Constellation",
            "days_until_prefix" to "Days until",
            "days_until_suffix" to "",
            "lucky_number" to "Lucky No",
            "lucky_color" to "Lucky Color",
            "forecast_title" to "Local & 3-Day Weather Forecast",
            "add_anniversary" to "+ Add Anniversary",
            "check_in" to "📍 Location Check-in",
            "save_anniversary" to "Save Anniversary",
            "anniversary_name" to "Anniversary Name",
            "anniversary_date" to "Anniversary Date",
            "dark_mode_system" to "Follow System",
            "dark_mode_on" to "Always On",
            "dark_mode_off" to "Always Off",
            "workday_chip" to "Workday",
            "weekend_chip" to "Weekend",
            "result_title_workday" to "Workday Calculation Result",
            "result_title_natural" to "Calendar Day Calculation Result"
        )

        val stringsJa = mapOf(
            "app_title" to "日付電卓",
            "tab_home" to "ホーム",
            "tab_calc" to "日付計算",
            "tab_countdown" to "カウントダウン",
            "tab_anniversary" to "記念日",
            "tab_lunar" to "旧暦変換",
            "tab_age" to "年齢計算",
            "settings_language" to "言語設定",
            "settings_theme" to "テーマ配色",
            "settings_dark_mode" to "ダークモード",
            "settings_home_config" to "ホーム表示項目設定",
            "settings_region" to "国・地域選択",
            "settings_gps_auto" to "GPS自動位置識別",
            "settings_sync_holidays" to "祝日データを同期",
            "home_show_screen" to "ホーム画面を表示",
            "home_calendar" to "月カレンダー",
            "home_almanac" to "暦宜忌",
            "home_solar_terms" to "二十四節気",
            "home_lunar" to "旧暦日付",
            "home_zodiac" to "星座と運勢",
            "home_weather" to "天気予報",
            "workday" to "稼働日",
            "natural_day" to "自然日",
            "solar" to "新暦",
            "lunar" to "旧暦",
            "target_date" to "目標日付",
            "base_date" to "開始日付",
            "settings_title" to "設定",
            "history_title" to "履歴",
            "add_countdown" to "+ カウントダウン追加",
            "common_countdown" to "プリセット",
            "fixed_countdown" to "固定カウントダウン",
            "today" to "今日",
            "yesterday" to "昨日",
            "plus_1w" to "+1週",
            "minus_1w" to "-1週",
            "mode_forward" to "日数加減",
            "mode_reverse" to "期間計算",
            "multi_stage_btn" to "複数段階",
            "add_stage_btn" to "次の段階を追加",
            "save_record" to "記録を保存",
            "diff_natural" to "自然日数差",
            "diff_workday" to "稼働日数差",
            "clear_history" to "履歴消去",
            "no_history" to "履歴がありません",
            "select_birth_date" to "生年月日を選択",
            "select_start_date" to "開始日を選択",
            "select_target_date" to "目標日を選択",
            "exact_age" to "正確な現在の年齢",
            "next_birthday_days" to "次の誕生日まであと",
            "days_unit" to "日",
            "weeks_unit" to "週間",
            "months_unit" to "ヶ月",
            "years_unit" to "歳",
            "total_days" to "通算生存日数",
            "total_weeks" to "通算生存週数",
            "zodiac_sign" to "干支",
            "constellation" to "星座",
            "days_until_prefix" to "",
            "days_until_suffix" to "まであと",
            "lucky_number" to "ラッキー数字",
            "lucky_color" to "ラッキーカラー",
            "forecast_title" to "当地および今後3日間の天気予報",
            "add_anniversary" to "+ 記念日追加",
            "check_in" to "📍 位置情報チェックイン",
            "save_anniversary" to "記念日を保存",
            "anniversary_name" to "記念日名称",
            "anniversary_date" to "記念日日付",
            "dark_mode_system" to "システムに従う",
            "dark_mode_on" to "常時ON",
            "dark_mode_off" to "常時OFF",
            "workday_chip" to "稼働日",
            "weekend_chip" to "休業日",
            "result_title_workday" to "稼働日計算結果",
            "result_title_natural" to "自然日計算結果"
        )

        val stringsKo = mapOf(
            "app_title" to "날짜 계산기",
            "tab_home" to "홈",
            "tab_calc" to "날짜 계산",
            "tab_countdown" to "디데이",
            "tab_anniversary" to "기념일",
            "tab_lunar" to "음력 변환",
            "tab_age" to "나이 계산",
            "settings_language" to "언어 설정",
            "settings_theme" to "테마 색상",
            "settings_dark_mode" to "다크 모드",
            "settings_home_config" to "홈 화면 표시 항목 설정",
            "settings_region" to "국가 / 지역 선택",
            "settings_gps_auto" to "GPS 자동 위치 감지",
            "settings_sync_holidays" to "공휴일 데이터 동기화",
            "home_show_screen" to "홈 화면 표시",
            "home_calendar" to "달력",
            "home_almanac" to "황력",
            "home_solar_terms" to "24절기",
            "home_lunar" to "음력 날짜",
            "home_zodiac" to "별자리 운세",
            "home_weather" to "날씨 예보",
            "workday" to "근무일",
            "natural_day" to "자연일",
            "solar" to "양력",
            "lunar" to "음력",
            "target_date" to "목표 날짜",
            "base_date" to "시작 날짜",
            "settings_title" to "설정",
            "history_title" to "히스토리",
            "add_countdown" to "+ 디데이 추가",
            "common_countdown" to "추천 디데이",
            "fixed_countdown" to "고정 디데이",
            "today" to "오늘",
            "yesterday" to "어제",
            "plus_1w" to "+1주",
            "minus_1w" to "-1주",
            "mode_forward" to "일수 가감",
            "mode_reverse" to "기간 계산",
            "multi_stage_btn" to "다단계 모드",
            "add_stage_btn" to "다음 단계 추가",
            "save_record" to "기록 저장",
            "diff_natural" to "자연일 차이",
            "diff_workday" to "근무일 차이",
            "clear_history" to "히스토리 삭제",
            "no_history" to "히스토리 기록이 없습니다",
            "select_birth_date" to "생년월일 선택",
            "select_start_date" to "시작 날짜 선택",
            "select_target_date" to "목표 날짜 선택",
            "exact_age" to "현재 정확한 나이",
            "next_birthday_days" to "다음 생일까지 남은 일수",
            "days_unit" to "일",
            "weeks_unit" to "주",
            "months_unit" to "개월",
            "years_unit" to "세",
            "total_days" to "총 생존 일수",
            "total_weeks" to "총 생존 주수",
            "zodiac_sign" to "띠",
            "constellation" to "별자리",
            "days_until_prefix" to "",
            "days_until_suffix" to "까지 남은 시간",
            "lucky_number" to "행운의 숫자",
            "lucky_color" to "행운의 색상",
            "forecast_title" to "현지 및 향후 3일 날씨 예보",
            "add_anniversary" to "+ 기념일 추가",
            "check_in" to "📍 위치 체크인",
            "save_anniversary" to "기념일 저장",
            "anniversary_name" to "기념일 이름",
            "anniversary_date" to "기념일 날짜",
            "dark_mode_system" to "시스템 설정 따름",
            "dark_mode_on" to "항상 켜기",
            "dark_mode_off" to "항상 끄기",
            "workday_chip" to "근무일",
            "weekend_chip" to "휴무일",
            "result_title_workday" to "근무일 계산 결과",
            "result_title_natural" to "자연일 계산 결과"
        )

        val map = when (language) {
            AppLanguage.SIMPLIFIED_CHINESE -> stringsZhCn
            AppLanguage.TRADITIONAL_CHINESE -> stringsZhTw
            AppLanguage.ENGLISH -> stringsEn
            AppLanguage.JAPANESE -> stringsJa
            AppLanguage.KOREAN -> stringsKo
        }

        return map[key] ?: stringsZhCn[key] ?: key
    }
}
